/* Generated by           cobc 3.2.0 */
/* Generated from         /home/dlong/Source/repos/cobol/00-Setup/HELLO.cob */
/* Generated at           Dec 08 2025 20:16:52 */
/* GnuCOBOL build date    Jul 23 2025 00:00:00 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -x -locsql -L /usr/lib64/libocsql.so -q -g -fsource-location -ftraceall -Q --coverage -A --coverage -v /home/dlong/Source/repos/cobol/00-Setup/HELLO.cob */

#include <string.h> /* for memcpy, memcmp and friends */
#define  COB_KEYWORD_INLINE __inline
#include <libcob.h>

#define  COB_SOURCE_FILE		"/home/dlong/Source/repos/cobol/00-Setup/HELLO.cob"
#define  COB_PACKAGE_VERSION		"3.2"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Dec 08 2025 20:16:52"
#define  COB_MODULE_DATE		20251208
#define  COB_MODULE_TIME		201652

/* Global variables */
#include "HELLO.c.h"

/* Function prototypes */

static int		HELLO ();
static int		HELLO_ (const int);
static void		HELLO_module_init (cob_module *module);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (HELLO ());
}

/* Functions */

static void gc_module_so_init () __attribute__ ((constructor));
static void gc_module_so_init ()
{
  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
}

/* PROGRAM-ID 'HELLO' */

/* ENTRY 'HELLO' */

static int
HELLO ()
{
  return HELLO_ (0);
}

static int
HELLO_ (const int entry)
{
  /* Program local variables */
  #include "HELLO.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;
  frame_overflow = frame_ptr + 255 - 1;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 14        : Entry     HELLO                   : /home/dlong/Source/repos/cobol/00-Setup/HELLO.cob */
  l_2:;
#line 14 "/home/dlong/Source/repos/cobol/00-Setup/HELLO.cob"
  ENTRY_HELLO:	module->statement = STMT_ENTRY;
#line 105 "HELLO.c"
  module->module_stmt = 0x0010000E;
  cob_trace_entry (st_1);
  module->section_name = NULL;
  module->paragraph_name = NULL;
  cob_trace_sect (NULL);

  /* Line: 14        : Paragraph MAIN                    : /home/dlong/Source/repos/cobol/00-Setup/HELLO.cob */
#line 14 "/home/dlong/Source/repos/cobol/00-Setup/HELLO.cob"
  PARAGRAPH_MAIN_l_4:	module->statement = STMT_ENTRY;
#line 115 "HELLO.c"
  module->paragraph_name = st_2;
  cob_trace_para (st_2);

  /* Line: 15        : DISPLAY            : /home/dlong/Source/repos/cobol/00-Setup/HELLO.cob */
#line 15 "/home/dlong/Source/repos/cobol/00-Setup/HELLO.cob"
  module->statement = STMT_DISPLAY;
#line 122 "HELLO.c"
  module->module_stmt = 0x0010000F;
  cob_trace_statement (STMT_DISPLAY);
  cob_display (0, 1, 1, &c_1);

  /* Line: 16        : STOP RUN           : /home/dlong/Source/repos/cobol/00-Setup/HELLO.cob */
#line 16 "/home/dlong/Source/repos/cobol/00-Setup/HELLO.cob"
  module->statement = STMT_STOP_RUN;
#line 130 "HELLO.c"
  module->module_stmt = 0x00100010;
  cob_trace_statement (STMT_STOP_RUN);
  cob_stop_run (b_2);

  /* Line: 18        : last source line                  :/home/dlong/Source/repos/cobol/00-Setup/HELLO.cob */
#line 18 "/home/dlong/Source/repos/cobol/00-Setup/HELLO.cob"
  module->module_stmt = 0x00100012;
#line 138 "HELLO.c"
  cob_nop ();


  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Trace program exit */
  cob_trace_exit (st_1);

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;
  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_module_path = cob_glob_ptr->cob_main_argv0;

  HELLO_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  b_2 = 0;


  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  initialized = 0;

  P_clear_decimal:
  return 0;

}

/* End PROGRAM-ID 'HELLO' */

/* Initialize module structure for HELLO */
static void HELLO_module_init (cob_module *module)
{
  module->module_name = "HELLO";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->gc_version = COB_PACKAGE_VERSION;
  module->module_entry.funcptr = (void *(*)())HELLO;
  module->module_cancel.funcptr = (void *(*)())HELLO_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 1;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 6;
  module->flag_dump_ready = 0;
  module->xml_mode = 1;
  module->module_stmt = 0;
  module->module_sources = st_source_files;
}

/* End functions */

