/* Generated by           cobc 3.2.0 */
/* Generated from         /home/dlong/Source/repos/cobol/00-Setup/HELLO.cob */
/* Generated at           Dec 08 2025 20:16:52 */
/* GnuCOBOL build date    Jul 23 2025 00:00:00 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -x -locsql -L /usr/lib64/libocsql.so -q -g -fsource-location -ftraceall -Q --coverage -A --coverage -v /home/dlong/Source/repos/cobol/00-Setup/HELLO.cob */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Attributes */

static const cob_field_attr a_1 =	{0x21,   0,   0, 0x1000, NULL};


/* Constants */
static const cob_field c_1	= {11, (cob_u8_ptr)"HELLO WORLD", &a_1};


/* Strings */
static const char st_1[]	= "HELLO";
static const char st_2[]	= "MAIN";


/* Source file names */
static const char *st_source_files[]	= { "" 
		,"/home/dlong/Source/repos/cobol/00-Setup/HELLO.cob"};

#define cob_nop	if (!module) cob_nop

