/* Generated by           cobc 3.2.0 */
/* Generated from         /home/dlong/Source/repos/cobol/01-Assignment/CALAGE.cob */
/* Generated at           Dec 08 2025 20:17:19 */
/* GnuCOBOL build date    Jul 23 2025 00:00:00 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -x -locsql -L /usr/lib64/libocsql.so -q -g -fsource-location -ftraceall -Q --coverage -A --coverage -v /home/dlong/Source/repos/cobol/01-Assignment/CALAGE.cob */

#include <string.h> /* for memcpy, memcmp and friends */
#define  COB_KEYWORD_INLINE __inline
#include <gmp.h>
#include <libcob.h>

#define  COB_SOURCE_FILE		"/home/dlong/Source/repos/cobol/01-Assignment/CALAGE.cob"
#define  COB_PACKAGE_VERSION		"3.2"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Dec 08 2025 20:17:19"
#define  COB_MODULE_DATE		20251208
#define  COB_MODULE_TIME		201719

/* Global variables */
#include "CALAGE.c.h"

/* Function prototypes */

static int		CALCAGE ();
static int		CALCAGE_ (const int);
static void		CALCAGE_module_init (cob_module *module);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (CALCAGE ());
}

/* Functions */

static void gc_module_so_init () __attribute__ ((constructor));
static void gc_module_so_init ()
{
  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
}

/* PROGRAM-ID 'CALCAGE' */

/* ENTRY 'CALCAGE' */

static int
CALCAGE ()
{
  return CALCAGE_ (0);
}

static int
CALCAGE_ (const int entry)
{
  /* Program local variables */
  #include "CALAGE.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;
  frame_overflow = frame_ptr + 255 - 1;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Allocate decimal numbers */
  cob_decimal_alloc (2, &d_0, &d_1);

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 35        : Entry     CALCAGE                 : /home/dlong/Source/repos/cobol/01-Assignment/CALAGE.cob */
  l_2:;
#line 35 "/home/dlong/Source/repos/cobol/01-Assignment/CALAGE.cob"
  ENTRY_CALCAGE:	module->statement = STMT_ENTRY;
#line 109 "CALAGE.c"
  module->module_stmt = 0x00100023;
  cob_trace_entry (st_1);
  module->section_name = NULL;
  module->paragraph_name = NULL;
  cob_trace_sect (NULL);

  /* Line: 35        : Paragraph MAIN                    : /home/dlong/Source/repos/cobol/01-Assignment/CALAGE.cob */
#line 35 "/home/dlong/Source/repos/cobol/01-Assignment/CALAGE.cob"
  PARAGRAPH_MAIN_l_4:	module->statement = STMT_ENTRY;
#line 119 "CALAGE.c"
  module->paragraph_name = st_2;
  cob_trace_para (st_2);

  /* Line: 36        : PERFORM            : /home/dlong/Source/repos/cobol/01-Assignment/CALAGE.cob */
#line 36 "/home/dlong/Source/repos/cobol/01-Assignment/CALAGE.cob"
  module->statement = STMT_PERFORM;
#line 126 "CALAGE.c"
  module->module_stmt = 0x00100024;
  cob_trace_statement (STMT_PERFORM);
  /* PERFORM INITIALIZE-PARA */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 5;
  frame_ptr->return_address_ptr = &&l_8;
  goto l_5;
  l_8:
  frame_ptr--;

  /* Line: 37        : PERFORM            : /home/dlong/Source/repos/cobol/01-Assignment/CALAGE.cob */
#line 37 "/home/dlong/Source/repos/cobol/01-Assignment/CALAGE.cob"
  module->statement = STMT_PERFORM;
#line 142 "CALAGE.c"
  module->module_stmt = 0x00100025;
  cob_trace_statement (STMT_PERFORM);
  /* PERFORM PROCESS-PARA */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 6;
  frame_ptr->return_address_ptr = &&l_9;
  goto l_6;
  l_9:
  frame_ptr--;

  /* Line: 38        : PERFORM            : /home/dlong/Source/repos/cobol/01-Assignment/CALAGE.cob */
#line 38 "/home/dlong/Source/repos/cobol/01-Assignment/CALAGE.cob"
  module->statement = STMT_PERFORM;
#line 158 "CALAGE.c"
  module->module_stmt = 0x00100026;
  cob_trace_statement (STMT_PERFORM);
  /* PERFORM TERMINATE-PARA */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 7;
  frame_ptr->return_address_ptr = &&l_10;
  goto l_7;
  l_10:
  frame_ptr--;

  /* Line: 43        : Paragraph INITIALIZE-PARA         : /home/dlong/Source/repos/cobol/01-Assignment/CALAGE.cob */
  l_5:;
#line 43 "/home/dlong/Source/repos/cobol/01-Assignment/CALAGE.cob"
  PARAGRAPH_INITIALIZE__PARA_l_5:	module->statement = STMT_ENTRY;
#line 175 "CALAGE.c"
  module->module_stmt = 0x0010002B;
  module->paragraph_name = st_3;
  cob_trace_para (st_3);

  /* Line: 44        : OPEN               : /home/dlong/Source/repos/cobol/01-Assignment/CALAGE.cob */
#line 44 "/home/dlong/Source/repos/cobol/01-Assignment/CALAGE.cob"
  module->statement = STMT_OPEN;
#line 183 "CALAGE.c"
  module->module_stmt = 0x0010002C;
  cob_trace_statement (STMT_OPEN);
  cob_open (h_EMPLOYEE, COB_OPEN_INPUT, 0, NULL);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_11;
    goto l_1;
    l_11:
    frame_ptr--;
  }

  /* Line: 45        : MOVE               : /home/dlong/Source/repos/cobol/01-Assignment/CALAGE.cob */
#line 45 "/home/dlong/Source/repos/cobol/01-Assignment/CALAGE.cob"
  module->statement = STMT_MOVE;
#line 203 "CALAGE.c"
  module->module_stmt = 0x0010002D;
  cob_trace_statement (STMT_MOVE);
  *(b_28) = 32;

  /* Line: 46        : MOVE               : /home/dlong/Source/repos/cobol/01-Assignment/CALAGE.cob */
#line 46 "/home/dlong/Source/repos/cobol/01-Assignment/CALAGE.cob"
  module->statement = STMT_MOVE;
#line 211 "CALAGE.c"
  module->module_stmt = 0x0010002E;
  cob_trace_statement (STMT_MOVE);
  cob_move (cob_intr_current_date (0, 0), &f_29);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 5)
    goto *frame_ptr->return_address_ptr;

  /* Line: 51        : Paragraph PROCESS-PARA            : /home/dlong/Source/repos/cobol/01-Assignment/CALAGE.cob */
  l_6:;
#line 51 "/home/dlong/Source/repos/cobol/01-Assignment/CALAGE.cob"
  PARAGRAPH_PROCESS__PARA_l_6:	module->statement = STMT_ENTRY;
#line 224 "CALAGE.c"
  module->module_stmt = 0x00100033;
  module->paragraph_name = st_4;
  cob_trace_para (st_4);

  /* Line: 52        : READ               : /home/dlong/Source/repos/cobol/01-Assignment/CALAGE.cob */
#line 52 "/home/dlong/Source/repos/cobol/01-Assignment/CALAGE.cob"
  module->statement = STMT_READ;
#line 232 "CALAGE.c"
  module->module_stmt = 0x00100034;
  cob_trace_statement (STMT_READ);
  cob_read_next (h_EMPLOYEE, NULL, 1);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    if (cob_glob_ptr->cob_exception_code == 0x0501)
    {

      /* Line: 53        : MOVE               : /home/dlong/Source/repos/cobol/01-Assignment/CALAGE.cob */
#line 53 "/home/dlong/Source/repos/cobol/01-Assignment/CALAGE.cob"
      module->statement = STMT_MOVE;
#line 244 "CALAGE.c"
      module->module_stmt = 0x00100035;
      cob_trace_statement (STMT_MOVE);
      *(b_28) = 89;
    }
    else
    {
      /* USE PROCEDURE Default Error Handler */
      frame_ptr++;
      if (unlikely(frame_ptr == frame_overflow))
      	cob_fatal_error (COB_FERROR_STACK);
      frame_ptr->perform_through = 1;
      frame_ptr->return_address_ptr = &&l_12;
      goto l_1;
      l_12:
      frame_ptr--;
    }
  }
  else
  {
    memmove (b_27, b_27, 48);
  }

  /* Line: 55        : PERFORM            : /home/dlong/Source/repos/cobol/01-Assignment/CALAGE.cob */
#line 55 "/home/dlong/Source/repos/cobol/01-Assignment/CALAGE.cob"
  module->statement = STMT_PERFORM;
#line 270 "CALAGE.c"
  module->module_stmt = 0x00100037;
  cob_trace_statement (STMT_PERFORM);
  for (;;)
  {
    /* Line: 55        : UNTIL              : /home/dlong/Source/repos/cobol/01-Assignment/CALAGE.cob */
#line 55 "/home/dlong/Source/repos/cobol/01-Assignment/CALAGE.cob"
    module->statement = STMT_UNTIL;
#line 278 "CALAGE.c"
    module->module_stmt = 0x00100037;
    cob_trace_statement (STMT_UNTIL);
    if (((int)(int)(*(b_28) - (unsigned char)'Y') == 0))
      break;

    /* Line: 57        : COMPUTE            : /home/dlong/Source/repos/cobol/01-Assignment/CALAGE.cob */
#line 57 "/home/dlong/Source/repos/cobol/01-Assignment/CALAGE.cob"
    module->statement = STMT_COMPUTE;
#line 287 "CALAGE.c"
    module->module_stmt = 0x00100039;
    cob_trace_statement (STMT_COMPUTE);
    cob_decimal_set_field (d_0, &f_30);
    cob_decimal_set_field (d_1, &f_22);
    cob_decimal_sub (d_0, d_1);
    cob_decimal_sub (d_0, dc_1);
    cob_decimal_get_field (d_0, &f_33, 0);

    /* Line: 58        : IF                 : /home/dlong/Source/repos/cobol/01-Assignment/CALAGE.cob */
#line 58 "/home/dlong/Source/repos/cobol/01-Assignment/CALAGE.cob"
    module->statement = STMT_IF;
#line 299 "CALAGE.c"
    module->module_stmt = 0x0010003A;
    cob_trace_statement (STMT_IF);
    if (((int)memcmp (b_29 + 4, b_27 + 43, 2) > 0))
    {

      /* Line: 59        : COMPUTE            : /home/dlong/Source/repos/cobol/01-Assignment/CALAGE.cob */
#line 59 "/home/dlong/Source/repos/cobol/01-Assignment/CALAGE.cob"
      module->statement = STMT_COMPUTE;
#line 308 "CALAGE.c"
      module->module_stmt = 0x0010003B;
      cob_trace_statement (STMT_COMPUTE);
      cob_decimal_set_field (d_0, &f_33);
      cob_decimal_add (d_0, dc_1);
      cob_decimal_get_field (d_0, &f_33, 0);
    }
    else
    {
      /* ELSE */

      /* Line: 61        : IF                 : /home/dlong/Source/repos/cobol/01-Assignment/CALAGE.cob */
#line 61 "/home/dlong/Source/repos/cobol/01-Assignment/CALAGE.cob"
      module->statement = STMT_IF;
#line 322 "CALAGE.c"
      module->module_stmt = 0x0010003D;
      cob_trace_statement (STMT_IF);
      if (((int)memcmp (b_29 + 4, b_27 + 43, 2) == 0))
      {

        /* Line: 62        : IF                 : /home/dlong/Source/repos/cobol/01-Assignment/CALAGE.cob */
#line 62 "/home/dlong/Source/repos/cobol/01-Assignment/CALAGE.cob"
        module->statement = STMT_IF;
#line 331 "CALAGE.c"
        module->module_stmt = 0x0010003E;
        cob_trace_statement (STMT_IF);
        if (((int)memcmp (b_29 + 6, b_27 + 46, 2) >= 0))
        {

          /* Line: 63        : COMPUTE            : /home/dlong/Source/repos/cobol/01-Assignment/CALAGE.cob */
#line 63 "/home/dlong/Source/repos/cobol/01-Assignment/CALAGE.cob"
          module->statement = STMT_COMPUTE;
#line 340 "CALAGE.c"
          module->module_stmt = 0x0010003F;
          cob_trace_statement (STMT_COMPUTE);
          cob_decimal_set_field (d_0, &f_33);
          cob_decimal_add (d_0, dc_1);
          cob_decimal_get_field (d_0, &f_33, 0);
        }
      }
    }

    /* Line: 68        : DISPLAY            : /home/dlong/Source/repos/cobol/01-Assignment/CALAGE.cob */
#line 68 "/home/dlong/Source/repos/cobol/01-Assignment/CALAGE.cob"
    module->statement = STMT_DISPLAY;
#line 353 "CALAGE.c"
    module->module_stmt = 0x00100044;
    cob_trace_statement (STMT_DISPLAY);
    cob_display (0, 1, 3, &f_17, &c_2, &f_33);

    /* Line: 70        : READ               : /home/dlong/Source/repos/cobol/01-Assignment/CALAGE.cob */
#line 70 "/home/dlong/Source/repos/cobol/01-Assignment/CALAGE.cob"
    module->statement = STMT_READ;
#line 361 "CALAGE.c"
    module->module_stmt = 0x00100046;
    cob_trace_statement (STMT_READ);
    cob_read_next (h_EMPLOYEE, NULL, 1);
    if (unlikely(cob_glob_ptr->cob_exception_code != 0))
    {
      if (cob_glob_ptr->cob_exception_code == 0x0501)
      {

        /* Line: 71        : MOVE               : /home/dlong/Source/repos/cobol/01-Assignment/CALAGE.cob */
#line 71 "/home/dlong/Source/repos/cobol/01-Assignment/CALAGE.cob"
        module->statement = STMT_MOVE;
#line 373 "CALAGE.c"
        module->module_stmt = 0x00100047;
        cob_trace_statement (STMT_MOVE);
        *(b_28) = 89;
      }
      else
      {
        /* USE PROCEDURE Default Error Handler */
        frame_ptr++;
        if (unlikely(frame_ptr == frame_overflow))
        	cob_fatal_error (COB_FERROR_STACK);
        frame_ptr->perform_through = 1;
        frame_ptr->return_address_ptr = &&l_13;
        goto l_1;
        l_13:
        frame_ptr--;
      }
    }
    else
    {
      memmove (b_27, b_27, 48);
    }
  }

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 6)
    goto *frame_ptr->return_address_ptr;

  /* Line: 78        : Paragraph TERMINATE-PARA          : /home/dlong/Source/repos/cobol/01-Assignment/CALAGE.cob */
  l_7:;
#line 78 "/home/dlong/Source/repos/cobol/01-Assignment/CALAGE.cob"
  PARAGRAPH_TERMINATE__PARA_l_7:	module->statement = STMT_ENTRY;
#line 405 "CALAGE.c"
  module->module_stmt = 0x0010004E;
  module->paragraph_name = st_5;
  cob_trace_para (st_5);

  /* Line: 79        : CLOSE              : /home/dlong/Source/repos/cobol/01-Assignment/CALAGE.cob */
#line 79 "/home/dlong/Source/repos/cobol/01-Assignment/CALAGE.cob"
  module->statement = STMT_CLOSE;
#line 413 "CALAGE.c"
  module->module_stmt = 0x0010004F;
  cob_trace_statement (STMT_CLOSE);
  cob_close (h_EMPLOYEE, NULL, 0, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_14;
    goto l_1;
    l_14:
    frame_ptr--;
  }

  /* Line: 80        : STOP RUN           : /home/dlong/Source/repos/cobol/01-Assignment/CALAGE.cob */
#line 80 "/home/dlong/Source/repos/cobol/01-Assignment/CALAGE.cob"
  module->statement = STMT_STOP_RUN;
#line 433 "CALAGE.c"
  module->module_stmt = 0x00100050;
  cob_trace_statement (STMT_STOP_RUN);
  cob_stop_run (b_2);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 7)
    goto *frame_ptr->return_address_ptr;

  /* Line: 81        : last source line                  :/home/dlong/Source/repos/cobol/01-Assignment/CALAGE.cob */
#line 81 "/home/dlong/Source/repos/cobol/01-Assignment/CALAGE.cob"
  module->module_stmt = 0x00100051;
#line 445 "CALAGE.c"
  cob_nop ();


  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Trace program exit */
  cob_trace_exit (st_1);

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;


  /* Line: 0         : Paragraph Default Error Handler   : /home/dlong/Source/repos/cobol/01-Assignment/CALAGE.cob */
  l_1:;

  if (!(cob_glob_ptr->cob_error_file->flag_select_features & COB_SELECT_FILE_STATUS))
  	cob_fatal_error (COB_FERROR_FILE);

  /* Implicit Default Error Handler return */
  if (frame_ptr->perform_through == 1)
    goto *frame_ptr->return_address_ptr;

  /* Fatal error if reached */
  cob_fatal_error (COB_FERROR_CODEGEN);

  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_module_path = cob_glob_ptr->cob_main_argv0;

  CALCAGE_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  b_2 = 0;

  /* initialize field WS-EMP-EOF */
#line 25 "/home/dlong/Source/repos/cobol/01-Assignment/CALAGE.cob"
  cob_nop ();
#line 517 "CALAGE.c"
  *(cob_u8_ptr)(b_28) = (unsigned char)' ';

  /* initialize field WS-TODAY */
#line 27 "/home/dlong/Source/repos/cobol/01-Assignment/CALAGE.cob"
  cob_nop ();
#line 523 "CALAGE.c"
  memset (b_29, (unsigned char)'0', 8);

  /* initialize field WS-AGE */
#line 32 "/home/dlong/Source/repos/cobol/01-Assignment/CALAGE.cob"
  cob_nop ();
#line 529 "CALAGE.c"
  memset (b_33, (unsigned char)'0', 3);


  /* File initialization for EMPLOYEE */
  cob_file_malloc (&h_EMPLOYEE, NULL, 0, 0);
  h_EMPLOYEE->select_name = (const char *)"EMPLOYEE";
  h_EMPLOYEE->file_status = h_EMPLOYEE_status;
  memset (h_EMPLOYEE_status, '0', 2);
  h_EMPLOYEE->assign = (cob_field *)&c_3;
  h_EMPLOYEE->record = &f_27;
  h_EMPLOYEE->variable_record = NULL;
  h_EMPLOYEE->record_min = 0;
  h_EMPLOYEE->record_max = 48;
  h_EMPLOYEE->file = NULL;
  h_EMPLOYEE->organization = 1;
  h_EMPLOYEE->access_mode = 1;
  h_EMPLOYEE->lock_mode = 0;
  h_EMPLOYEE->open_mode = 0;
  h_EMPLOYEE->flag_optional = 0;
  h_EMPLOYEE->flag_line_adv = 0;
  h_EMPLOYEE->flag_select_features = 0;

  /* Set Decimal Constant values */
  dc_1 = &kc_1;
  cob_decimal_init (dc_1);
  cob_decimal_set_field (dc_1, (cob_field *)&c_1);


  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  initialized = 0;

  P_clear_decimal:
  /* Clear Decimal Constant values */
  cob_decimal_clear (dc_1);
  dc_1 = NULL;

  return 0;

}

/* End PROGRAM-ID 'CALCAGE' */

/* Initialize module structure for CALCAGE */
static void CALCAGE_module_init (cob_module *module)
{
  module->module_name = "CALCAGE";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->gc_version = COB_PACKAGE_VERSION;
  module->module_entry.funcptr = (void *(*)())CALCAGE;
  module->module_cancel.funcptr = (void *(*)())CALCAGE_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 1;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 6;
  module->flag_dump_ready = 0;
  module->xml_mode = 1;
  module->module_stmt = 0;
  module->module_sources = st_source_files;
}

/* End functions */

