/* Generated by           cobc 3.2.0 */
/* Generated from         /home/dlong/Source/repos/cobol/01-Assignment/CALAGE.cob */
/* Generated at           Dec 08 2025 20:17:19 */
/* GnuCOBOL build date    Jul 23 2025 00:00:00 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -x -locsql -L /usr/lib64/libocsql.so -q -g -fsource-location -ftraceall -Q --coverage -A --coverage -v /home/dlong/Source/repos/cobol/01-Assignment/CALAGE.cob */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Attributes */

static const cob_field_attr a_1 =	{0x10,   1,   0, 0x1000, NULL};
static const cob_field_attr a_2 =	{0x01,   0,   0, 0x0000, NULL};
static const cob_field_attr a_3 =	{0x10,   4,   0, 0x0000, NULL};
static const cob_field_attr a_4 =	{0x10,   3,   0, 0x0000, NULL};
static const cob_field_attr a_5 =	{0x21,   0,   0, 0x1000, NULL};
static const cob_field_attr a_6 =	{0x21,   0,   0, 0x0000, NULL};


/* Constants */
static const cob_field c_1	= {1, (cob_u8_ptr)"1", &a_1};
static const cob_field c_2	= {1, (cob_u8_ptr)" ", &a_5};
static const cob_field c_3	= {11, (cob_u8_ptr)"./input.dta", &a_5};


/* Strings */
static const char st_1[]	= "CALCAGE";
static const char st_2[]	= "MAIN";
static const char st_3[]	= "INITIALIZE-PARA";
static const char st_4[]	= "PROCESS-PARA";
static const char st_5[]	= "TERMINATE-PARA";


/* Source file names */
static const char *st_source_files[]	= { "" 
		,"/home/dlong/Source/repos/cobol/01-Assignment/CALAGE.cob"};

#define cob_nop	if (!module) cob_nop


/* Decimal constants */
static	cob_decimal	kc_1;
static	cob_decimal	*dc_1 = NULL;

