/* Generated by           cobc 3.2.0 */
/* Generated from         /home/dlong/Source/repos/cobol/02-Assignment/CALAGE.cob */
/* Generated at           Dec 08 2025 20:18:56 */
/* GnuCOBOL build date    Jul 23 2025 00:00:00 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -x -locsql -L /usr/lib64/libocsql.so -q -g -fsource-location -ftraceall -Q --coverage -A --coverage -v /home/dlong/Source/repos/cobol/02-Assignment/CALAGE.cob */

/* Program local variables for 'CALCAGE' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;

/* Decimal structures */
cob_decimal	*d_0 = NULL;
cob_decimal	*d_1 = NULL;


/* File EMPLOYEE */
static cob_file		*h_EMPLOYEE = NULL;
static unsigned char	h_EMPLOYEE_status[4];

/* File EMPOUT */
static cob_file		*h_EMPOUT = NULL;
static unsigned char	h_EMPOUT_status[4];

/* LINKAGE SECTION (Items not referenced by USING clause) */
static unsigned char	*b_9 = NULL;  /* XML-NAMESPACE */
static unsigned char	*b_10 = NULL;  /* XML-NAMESPACE-PREFIX */
static unsigned char	*b_11 = NULL;  /* XML-NNAMESPACE */
static unsigned char	*b_12 = NULL;  /* XML-NNAMESPACE-PREFIX */
static unsigned char	*b_13 = NULL;  /* XML-NTEXT */
static unsigned char	*b_14 = NULL;  /* XML-TEXT */


/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame	*frame_overflow;
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Data storage */
static int	b_2;	/* RETURN-CODE */
static cob_u8_t	b_27[48] __attribute__((aligned));	/* EMPLOYEE Record */
static cob_u8_t	b_34[51] __attribute__((aligned));	/* EMPOUT Record */
static cob_u8_t	b_35[1] __attribute__((aligned));	/* WS-EMP-EOF */
static cob_u8_t	b_36[8] __attribute__((aligned));	/* WS-TODAY */
static cob_u8_t	b_40[3] __attribute__((aligned));	/* WS-AGE */

/* End of local data storage */


/* Fields (local) */
static cob_field f_17	= {48, b_27, &a_2};	/* EMPLOYEE-FILE */
static cob_field f_22	= {4, b_27 + 38, &a_3};	/* EMPDOBY */
static cob_field f_27	= {48, b_27, &a_7};	/* EMPLOYEE Record */
static cob_field f_28	= {51, b_34, &a_2};	/* EMPOUT-FILE */
static cob_field f_33	= {3, b_34 + 48, &a_5};	/* EMPOAGE */
static cob_field f_34	= {51, b_34, &a_7};	/* EMPOUT Record */
static cob_field f_36	= {8, b_36, &a_2};	/* WS-TODAY */
static cob_field f_37	= {4, b_36, &a_3};	/* WS-TODAY-Y */
static cob_field f_40	= {3, b_40, &a_4};	/* WS-AGE */

/* End of fields */

