/* Generated by           cobc 3.2.0 */
/* Generated from         /home/dlong/Source/repos/cobol/04-Assignment/CALAGE.cob */
/* Generated at           Dec 08 2025 20:21:05 */
/* GnuCOBOL build date    Jul 23 2025 00:00:00 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -x -locsql -L /usr/lib64/libocsql.so -q -g -fsource-location -ftraceall -Q --coverage -A --coverage -v /home/dlong/Source/repos/cobol/04-Assignment/CALAGE.cob */

/* Program local variables for 'CALCAGE-SEP-COMP' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;

/* Decimal structures */
cob_decimal	*d_0 = NULL;
cob_decimal	*d_1 = NULL;


/* File EMPLOYEE */
static cob_file		*h_EMPLOYEE = NULL;
static unsigned char	h_EMPLOYEE_status[4];

/* LINKAGE SECTION (Items not referenced by USING clause) */
static unsigned char	*b_9 = NULL;  /* XML-NAMESPACE */
static unsigned char	*b_10 = NULL;  /* XML-NAMESPACE-PREFIX */
static unsigned char	*b_11 = NULL;  /* XML-NNAMESPACE */
static unsigned char	*b_12 = NULL;  /* XML-NNAMESPACE-PREFIX */
static unsigned char	*b_13 = NULL;  /* XML-NTEXT */
static unsigned char	*b_14 = NULL;  /* XML-TEXT */


/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame	*frame_overflow;
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Data storage */
static int	b_2;	/* RETURN-CODE */
static cob_u8_t	b_27[48] __attribute__((aligned));	/* EMPLOYEE Record */
static cob_u8_t	b_28[1] __attribute__((aligned));	/* WS-EMP-EOF */
static cob_u8_t	b_29[3] __attribute__((aligned));	/* AGE */
static cob_u8_t	b_30[3] __attribute__((aligned));	/* CA-AGE */
static cob_u8_t	b_31[4] __attribute__((aligned));	/* CA-YEAR */
static cob_u8_t	b_32[2] __attribute__((aligned));	/* CA-MONTH */
static cob_u8_t	b_33[2] __attribute__((aligned));	/* CA-DAY */
static cob_u8_t	b_34[8] __attribute__((aligned));	/* CA-TODAY */

/* End of local data storage */


/* Fields (local) */
static cob_field f_19	= {15, b_27 + 3, &a_2};	/* EMPFNM */
static cob_field f_20	= {20, b_27 + 18, &a_2};	/* EMPLNM */
static cob_field f_27	= {48, b_27, &a_2};	/* EMPLOYEE Record */
static cob_field f_29	= {3, b_29, &a_3};	/* AGE */
static cob_field f_30	= {3, b_30, &a_3};	/* CA-AGE */
static cob_field f_31	= {4, b_31, &a_5};	/* CA-YEAR */
static cob_field f_34	= {8, b_34, &a_4};	/* CA-TODAY */
static cob_field f_35	= {4, b_34, &a_5};	/* CA-TODAY-Y */

/* End of fields */

