/* Generated by           cobc 3.2.0 */
/* Generated from         /home/dlong/Source/repos/cobol/04-Assignment/CALAGE.cob */
/* Generated at           Dec 08 2025 20:21:05 */
/* GnuCOBOL build date    Jul 23 2025 00:00:00 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -x -locsql -L /usr/lib64/libocsql.so -q -g -fsource-location -ftraceall -Q --coverage -A --coverage -v /home/dlong/Source/repos/cobol/04-Assignment/CALAGE.cob */

#include <string.h> /* for memcpy, memcmp and friends */
#define  COB_KEYWORD_INLINE __inline
#include <gmp.h>
#include <libcob.h>

#define  COB_SOURCE_FILE		"/home/dlong/Source/repos/cobol/04-Assignment/CALAGE.cob"
#define  COB_PACKAGE_VERSION		"3.2"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Dec 08 2025 20:21:05"
#define  COB_MODULE_DATE		20251208
#define  COB_MODULE_TIME		202105

/* Global variables */
#include "CALAGE.c.h"

/* Function prototypes */

static int		CALCAGE__SEP__COMP ();
static int		CALCAGE__SEP__COMP_ (const int);
static void		CALCAGE__SEP__COMP_module_init (cob_module *module);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (CALCAGE__SEP__COMP ());
}

/* Functions */

static void gc_module_so_init () __attribute__ ((constructor));
static void gc_module_so_init ()
{
  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
}

/* PROGRAM-ID 'CALCAGE-SEP-COMP' */

/* ENTRY 'CALCAGE__SEP__COMP' */

static int
CALCAGE__SEP__COMP ()
{
  return CALCAGE__SEP__COMP_ (0);
}

static int
CALCAGE__SEP__COMP_ (const int entry)
{
  /* Program local variables */
  #include "CALAGE.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;
  frame_overflow = frame_ptr + 255 - 1;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Allocate decimal numbers */
  cob_decimal_alloc (2, &d_0, &d_1);

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 32        : Entry     CALCAGE-SEP-COMP        : /home/dlong/Source/repos/cobol/04-Assignment/CALAGE.cob */
  l_2:;
#line 32 "/home/dlong/Source/repos/cobol/04-Assignment/CALAGE.cob"
  ENTRY_CALCAGE__SEP__COMP:	module->statement = STMT_ENTRY;
#line 109 "CALAGE.c"
  module->module_stmt = 0x00100020;
  cob_trace_entry (st_1);
  module->section_name = NULL;
  module->paragraph_name = NULL;
  cob_trace_sect (NULL);

  /* Line: 32        : Paragraph MAIN                    : /home/dlong/Source/repos/cobol/04-Assignment/CALAGE.cob */
#line 32 "/home/dlong/Source/repos/cobol/04-Assignment/CALAGE.cob"
  PARAGRAPH_MAIN_l_4:	module->statement = STMT_ENTRY;
#line 119 "CALAGE.c"
  module->paragraph_name = st_2;
  cob_trace_para (st_2);

  /* Line: 33        : PERFORM            : /home/dlong/Source/repos/cobol/04-Assignment/CALAGE.cob */
#line 33 "/home/dlong/Source/repos/cobol/04-Assignment/CALAGE.cob"
  module->statement = STMT_PERFORM;
#line 126 "CALAGE.c"
  module->module_stmt = 0x00100021;
  cob_trace_statement (STMT_PERFORM);
  /* PERFORM INITIALIZE-PARA */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 5;
  frame_ptr->return_address_ptr = &&l_9;
  goto l_5;
  l_9:
  frame_ptr--;

  /* Line: 34        : PERFORM            : /home/dlong/Source/repos/cobol/04-Assignment/CALAGE.cob */
#line 34 "/home/dlong/Source/repos/cobol/04-Assignment/CALAGE.cob"
  module->statement = STMT_PERFORM;
#line 142 "CALAGE.c"
  module->module_stmt = 0x00100022;
  cob_trace_statement (STMT_PERFORM);
  /* PERFORM PROCESS-PARA */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 6;
  frame_ptr->return_address_ptr = &&l_10;
  goto l_6;
  l_10:
  frame_ptr--;

  /* Line: 35        : PERFORM            : /home/dlong/Source/repos/cobol/04-Assignment/CALAGE.cob */
#line 35 "/home/dlong/Source/repos/cobol/04-Assignment/CALAGE.cob"
  module->statement = STMT_PERFORM;
#line 158 "CALAGE.c"
  module->module_stmt = 0x00100023;
  cob_trace_statement (STMT_PERFORM);
  /* PERFORM TERMINATE-PARA */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 8;
  frame_ptr->return_address_ptr = &&l_11;
  goto l_8;
  l_11:
  frame_ptr--;

  /* Line: 40        : Paragraph INITIALIZE-PARA         : /home/dlong/Source/repos/cobol/04-Assignment/CALAGE.cob */
  l_5:;
#line 40 "/home/dlong/Source/repos/cobol/04-Assignment/CALAGE.cob"
  PARAGRAPH_INITIALIZE__PARA_l_5:	module->statement = STMT_ENTRY;
#line 175 "CALAGE.c"
  module->module_stmt = 0x00100028;
  module->paragraph_name = st_3;
  cob_trace_para (st_3);

  /* Line: 41        : OPEN               : /home/dlong/Source/repos/cobol/04-Assignment/CALAGE.cob */
#line 41 "/home/dlong/Source/repos/cobol/04-Assignment/CALAGE.cob"
  module->statement = STMT_OPEN;
#line 183 "CALAGE.c"
  module->module_stmt = 0x00100029;
  cob_trace_statement (STMT_OPEN);
  cob_open (h_EMPLOYEE, COB_OPEN_INPUT, 0, NULL);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_12;
    goto l_1;
    l_12:
    frame_ptr--;
  }

  /* Line: 42        : MOVE               : /home/dlong/Source/repos/cobol/04-Assignment/CALAGE.cob */
#line 42 "/home/dlong/Source/repos/cobol/04-Assignment/CALAGE.cob"
  module->statement = STMT_MOVE;
#line 203 "CALAGE.c"
  module->module_stmt = 0x0010002A;
  cob_trace_statement (STMT_MOVE);
  *(b_28) = 32;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 5)
    goto *frame_ptr->return_address_ptr;

  /* Line: 47        : Paragraph PROCESS-PARA            : /home/dlong/Source/repos/cobol/04-Assignment/CALAGE.cob */
  l_6:;
#line 47 "/home/dlong/Source/repos/cobol/04-Assignment/CALAGE.cob"
  PARAGRAPH_PROCESS__PARA_l_6:	module->statement = STMT_ENTRY;
#line 216 "CALAGE.c"
  module->module_stmt = 0x0010002F;
  module->paragraph_name = st_4;
  cob_trace_para (st_4);

  /* Line: 48        : READ               : /home/dlong/Source/repos/cobol/04-Assignment/CALAGE.cob */
#line 48 "/home/dlong/Source/repos/cobol/04-Assignment/CALAGE.cob"
  module->statement = STMT_READ;
#line 224 "CALAGE.c"
  module->module_stmt = 0x00100030;
  cob_trace_statement (STMT_READ);
  cob_read_next (h_EMPLOYEE, NULL, 1);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    if (cob_glob_ptr->cob_exception_code == 0x0501)
    {

      /* Line: 49        : MOVE               : /home/dlong/Source/repos/cobol/04-Assignment/CALAGE.cob */
#line 49 "/home/dlong/Source/repos/cobol/04-Assignment/CALAGE.cob"
      module->statement = STMT_MOVE;
#line 236 "CALAGE.c"
      module->module_stmt = 0x00100031;
      cob_trace_statement (STMT_MOVE);
      *(b_28) = 89;
    }
    else
    {
      /* USE PROCEDURE Default Error Handler */
      frame_ptr++;
      if (unlikely(frame_ptr == frame_overflow))
      	cob_fatal_error (COB_FERROR_STACK);
      frame_ptr->perform_through = 1;
      frame_ptr->return_address_ptr = &&l_13;
      goto l_1;
      l_13:
      frame_ptr--;
    }
  }
  else
  {
    memmove (b_27, b_27, 48);
  }

  /* Line: 51        : PERFORM            : /home/dlong/Source/repos/cobol/04-Assignment/CALAGE.cob */
#line 51 "/home/dlong/Source/repos/cobol/04-Assignment/CALAGE.cob"
  module->statement = STMT_PERFORM;
#line 262 "CALAGE.c"
  module->module_stmt = 0x00100033;
  cob_trace_statement (STMT_PERFORM);
  for (;;)
  {
    /* Line: 51        : UNTIL              : /home/dlong/Source/repos/cobol/04-Assignment/CALAGE.cob */
#line 51 "/home/dlong/Source/repos/cobol/04-Assignment/CALAGE.cob"
    module->statement = STMT_UNTIL;
#line 270 "CALAGE.c"
    module->module_stmt = 0x00100033;
    cob_trace_statement (STMT_UNTIL);
    if (((int)(int)(*(b_28) - (unsigned char)'Y') == 0))
      break;

    /* Line: 53        : MOVE               : /home/dlong/Source/repos/cobol/04-Assignment/CALAGE.cob */
#line 53 "/home/dlong/Source/repos/cobol/04-Assignment/CALAGE.cob"
    module->statement = STMT_MOVE;
#line 279 "CALAGE.c"
    module->module_stmt = 0x00100035;
    cob_trace_statement (STMT_MOVE);
    memcpy (b_32, b_27 + 43, 2);

    /* Line: 54        : MOVE               : /home/dlong/Source/repos/cobol/04-Assignment/CALAGE.cob */
#line 54 "/home/dlong/Source/repos/cobol/04-Assignment/CALAGE.cob"
    module->statement = STMT_MOVE;
#line 287 "CALAGE.c"
    module->module_stmt = 0x00100036;
    cob_trace_statement (STMT_MOVE);
    memcpy (b_33, b_27 + 46, 2);

    /* Line: 55        : MOVE               : /home/dlong/Source/repos/cobol/04-Assignment/CALAGE.cob */
#line 55 "/home/dlong/Source/repos/cobol/04-Assignment/CALAGE.cob"
    module->statement = STMT_MOVE;
#line 295 "CALAGE.c"
    module->module_stmt = 0x00100037;
    cob_trace_statement (STMT_MOVE);
    memcpy (b_31, b_27 + 38, 4);

    /* Line: 56        : PERFORM            : /home/dlong/Source/repos/cobol/04-Assignment/CALAGE.cob */
#line 56 "/home/dlong/Source/repos/cobol/04-Assignment/CALAGE.cob"
    module->statement = STMT_PERFORM;
#line 303 "CALAGE.c"
    module->module_stmt = 0x00100038;
    cob_trace_statement (STMT_PERFORM);
    /* PERFORM CALCULATE-AGE-PARA */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 7;
    frame_ptr->return_address_ptr = &&l_14;
    goto l_7;
    l_14:
    frame_ptr--;

    /* Line: 57        : MOVE               : /home/dlong/Source/repos/cobol/04-Assignment/CALAGE.cob */
#line 57 "/home/dlong/Source/repos/cobol/04-Assignment/CALAGE.cob"
    module->statement = STMT_MOVE;
#line 319 "CALAGE.c"
    module->module_stmt = 0x00100039;
    cob_trace_statement (STMT_MOVE);
    memcpy (b_29, b_30, 3);

    /* Line: 59        : DISPLAY            : /home/dlong/Source/repos/cobol/04-Assignment/CALAGE.cob */
#line 59 "/home/dlong/Source/repos/cobol/04-Assignment/CALAGE.cob"
    module->statement = STMT_DISPLAY;
#line 327 "CALAGE.c"
    module->module_stmt = 0x0010003B;
    cob_trace_statement (STMT_DISPLAY);
    cob_display (0, 1, 3, &f_19, &f_20, &f_29);

    /* Line: 61        : READ               : /home/dlong/Source/repos/cobol/04-Assignment/CALAGE.cob */
#line 61 "/home/dlong/Source/repos/cobol/04-Assignment/CALAGE.cob"
    module->statement = STMT_READ;
#line 335 "CALAGE.c"
    module->module_stmt = 0x0010003D;
    cob_trace_statement (STMT_READ);
    cob_read_next (h_EMPLOYEE, NULL, 1);
    if (unlikely(cob_glob_ptr->cob_exception_code != 0))
    {
      if (cob_glob_ptr->cob_exception_code == 0x0501)
      {

        /* Line: 62        : MOVE               : /home/dlong/Source/repos/cobol/04-Assignment/CALAGE.cob */
#line 62 "/home/dlong/Source/repos/cobol/04-Assignment/CALAGE.cob"
        module->statement = STMT_MOVE;
#line 347 "CALAGE.c"
        module->module_stmt = 0x0010003E;
        cob_trace_statement (STMT_MOVE);
        *(b_28) = 89;
      }
      else
      {
        /* USE PROCEDURE Default Error Handler */
        frame_ptr++;
        if (unlikely(frame_ptr == frame_overflow))
        	cob_fatal_error (COB_FERROR_STACK);
        frame_ptr->perform_through = 1;
        frame_ptr->return_address_ptr = &&l_15;
        goto l_1;
        l_15:
        frame_ptr--;
      }
    }
    else
    {
      memmove (b_27, b_27, 48);
    }
  }

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 6)
    goto *frame_ptr->return_address_ptr;

  /* Line: 4         : Paragraph CALCULATE-AGE-PARA      : CALC_AGE_PARA.cob */
  l_7:;
#line 4 "CALC_AGE_PARA.cob"
  PARAGRAPH_CALCULATE__AGE__PARA_l_7:	module->statement = STMT_ENTRY;
#line 379 "CALAGE.c"
  module->module_stmt = 0x00200004;
  module->paragraph_name = st_5;
  cob_trace_para (st_5);

  /* Line: 5         : MOVE               : CALC_AGE_PARA.cob */
#line 5 "CALC_AGE_PARA.cob"
  module->statement = STMT_MOVE;
#line 387 "CALAGE.c"
  module->module_stmt = 0x00200005;
  cob_trace_statement (STMT_MOVE);
  cob_move (cob_intr_current_date (0, 0), &f_34);

  /* Line: 7         : COMPUTE            : CALC_AGE_PARA.cob */
#line 7 "CALC_AGE_PARA.cob"
  module->statement = STMT_COMPUTE;
#line 395 "CALAGE.c"
  module->module_stmt = 0x00200007;
  cob_trace_statement (STMT_COMPUTE);
  cob_decimal_set_field (d_0, &f_35);
  cob_decimal_set_field (d_1, &f_31);
  cob_decimal_sub (d_0, d_1);
  cob_decimal_sub (d_0, dc_1);
  cob_decimal_get_field (d_0, &f_30, 0);

  /* Line: 8         : IF                 : CALC_AGE_PARA.cob */
#line 8 "CALC_AGE_PARA.cob"
  module->statement = STMT_IF;
#line 407 "CALAGE.c"
  module->module_stmt = 0x00200008;
  cob_trace_statement (STMT_IF);
  if (((int)memcmp (b_34 + 4, b_32, 2) > 0))
  {

    /* Line: 9         : COMPUTE            : CALC_AGE_PARA.cob */
#line 9 "CALC_AGE_PARA.cob"
    module->statement = STMT_COMPUTE;
#line 416 "CALAGE.c"
    module->module_stmt = 0x00200009;
    cob_trace_statement (STMT_COMPUTE);
    cob_decimal_set_field (d_0, &f_30);
    cob_decimal_add (d_0, dc_1);
    cob_decimal_get_field (d_0, &f_30, 0);
  }
  else
  {
    /* ELSE */

    /* Line: 11        : IF                 : CALC_AGE_PARA.cob */
#line 11 "CALC_AGE_PARA.cob"
    module->statement = STMT_IF;
#line 430 "CALAGE.c"
    module->module_stmt = 0x0020000B;
    cob_trace_statement (STMT_IF);
    if (((int)memcmp (b_34 + 4, b_32, 2) == 0))
    {

      /* Line: 12        : IF                 : CALC_AGE_PARA.cob */
#line 12 "CALC_AGE_PARA.cob"
      module->statement = STMT_IF;
#line 439 "CALAGE.c"
      module->module_stmt = 0x0020000C;
      cob_trace_statement (STMT_IF);
      if (((int)memcmp (b_34 + 6, b_33, 2) >= 0))
      {

        /* Line: 13        : COMPUTE            : CALC_AGE_PARA.cob */
#line 13 "CALC_AGE_PARA.cob"
        module->statement = STMT_COMPUTE;
#line 448 "CALAGE.c"
        module->module_stmt = 0x0020000D;
        cob_trace_statement (STMT_COMPUTE);
        cob_decimal_set_field (d_0, &f_30);
        cob_decimal_add (d_0, dc_1);
        cob_decimal_get_field (d_0, &f_30, 0);
      }
    }
  }

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 7)
    goto *frame_ptr->return_address_ptr;

  /* Line: 74        : Paragraph TERMINATE-PARA          : /home/dlong/Source/repos/cobol/04-Assignment/CALAGE.cob */
  l_8:;
#line 74 "/home/dlong/Source/repos/cobol/04-Assignment/CALAGE.cob"
  PARAGRAPH_TERMINATE__PARA_l_8:	module->statement = STMT_ENTRY;
#line 466 "CALAGE.c"
  module->module_stmt = 0x0010004A;
  module->paragraph_name = st_6;
  cob_trace_para (st_6);

  /* Line: 75        : CLOSE              : /home/dlong/Source/repos/cobol/04-Assignment/CALAGE.cob */
#line 75 "/home/dlong/Source/repos/cobol/04-Assignment/CALAGE.cob"
  module->statement = STMT_CLOSE;
#line 474 "CALAGE.c"
  module->module_stmt = 0x0010004B;
  cob_trace_statement (STMT_CLOSE);
  cob_close (h_EMPLOYEE, NULL, 0, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_16;
    goto l_1;
    l_16:
    frame_ptr--;
  }

  /* Line: 76        : STOP RUN           : /home/dlong/Source/repos/cobol/04-Assignment/CALAGE.cob */
#line 76 "/home/dlong/Source/repos/cobol/04-Assignment/CALAGE.cob"
  module->statement = STMT_STOP_RUN;
#line 494 "CALAGE.c"
  module->module_stmt = 0x0010004C;
  cob_trace_statement (STMT_STOP_RUN);
  cob_stop_run (b_2);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 8)
    goto *frame_ptr->return_address_ptr;

  /* Line: 77        : last source line                  :/home/dlong/Source/repos/cobol/04-Assignment/CALAGE.cob */
#line 77 "/home/dlong/Source/repos/cobol/04-Assignment/CALAGE.cob"
  module->module_stmt = 0x0010004D;
#line 506 "CALAGE.c"
  cob_nop ();


  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Trace program exit */
  cob_trace_exit (st_1);

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;


  /* Line: 0         : Paragraph Default Error Handler   : /home/dlong/Source/repos/cobol/04-Assignment/CALAGE.cob */
  l_1:;

  if (!(cob_glob_ptr->cob_error_file->flag_select_features & COB_SELECT_FILE_STATUS))
  	cob_fatal_error (COB_FERROR_FILE);

  /* Implicit Default Error Handler return */
  if (frame_ptr->perform_through == 1)
    goto *frame_ptr->return_address_ptr;

  /* Fatal error if reached */
  cob_fatal_error (COB_FERROR_CODEGEN);

  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_module_path = cob_glob_ptr->cob_main_argv0;

  CALCAGE__SEP__COMP_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  b_2 = 0;

  /* initialize field WS-EMP-EOF */
#line 25 "/home/dlong/Source/repos/cobol/04-Assignment/CALAGE.cob"
  cob_nop ();
#line 578 "CALAGE.c"
  *(cob_u8_ptr)(b_28) = (unsigned char)' ';

  /* initialize field AGE */
#line 26 "/home/dlong/Source/repos/cobol/04-Assignment/CALAGE.cob"
  cob_nop ();
#line 584 "CALAGE.c"
  memset (b_29, (unsigned char)'0', 3);

  /* initialize field CA-AGE */
#line 4 "CALC_AGE_DEF.cob"
  cob_nop ();
#line 590 "CALAGE.c"
  memset (b_30, (unsigned char)'0', 3);

  /* initialize field CA-YEAR */
#line 5 "CALC_AGE_DEF.cob"
  cob_nop ();
#line 596 "CALAGE.c"
  memset (b_31, (unsigned char)'0', 4);

  /* initialize field CA-MONTH */
#line 6 "CALC_AGE_DEF.cob"
  cob_nop ();
#line 602 "CALAGE.c"
  memset (b_32, (unsigned char)'0', 2);

  /* initialize field CA-DAY */
#line 7 "CALC_AGE_DEF.cob"
  cob_nop ();
#line 608 "CALAGE.c"
  memset (b_33, (unsigned char)'0', 2);

  /* initialize field CA-TODAY */
#line 8 "CALC_AGE_DEF.cob"
  cob_nop ();
#line 614 "CALAGE.c"
  memset (b_34, (unsigned char)'0', 8);


  /* File initialization for EMPLOYEE */
  cob_file_malloc (&h_EMPLOYEE, NULL, 0, 0);
  h_EMPLOYEE->select_name = (const char *)"EMPLOYEE";
  h_EMPLOYEE->file_status = h_EMPLOYEE_status;
  memset (h_EMPLOYEE_status, '0', 2);
  h_EMPLOYEE->assign = (cob_field *)&c_2;
  h_EMPLOYEE->record = &f_27;
  h_EMPLOYEE->variable_record = NULL;
  h_EMPLOYEE->record_min = 0;
  h_EMPLOYEE->record_max = 48;
  h_EMPLOYEE->file = NULL;
  h_EMPLOYEE->organization = 1;
  h_EMPLOYEE->access_mode = 1;
  h_EMPLOYEE->lock_mode = 0;
  h_EMPLOYEE->open_mode = 0;
  h_EMPLOYEE->flag_optional = 0;
  h_EMPLOYEE->flag_line_adv = 0;
  h_EMPLOYEE->flag_select_features = 0;

  /* Set Decimal Constant values */
  dc_1 = &kc_1;
  cob_decimal_init (dc_1);
  cob_decimal_set_field (dc_1, (cob_field *)&c_1);


  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  initialized = 0;

  P_clear_decimal:
  /* Clear Decimal Constant values */
  cob_decimal_clear (dc_1);
  dc_1 = NULL;

  return 0;

}

/* End PROGRAM-ID 'CALCAGE-SEP-COMP' */

/* Initialize module structure for CALCAGE-SEP-COMP */
static void CALCAGE__SEP__COMP_module_init (cob_module *module)
{
  module->module_name = "CALCAGE-SEP-COMP";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->gc_version = COB_PACKAGE_VERSION;
  module->module_entry.funcptr = (void *(*)())CALCAGE__SEP__COMP;
  module->module_cancel.funcptr = (void *(*)())CALCAGE__SEP__COMP_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 1;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 6;
  module->flag_dump_ready = 0;
  module->xml_mode = 1;
  module->module_stmt = 0;
  module->module_sources = st_source_files;
}

/* End functions */

